name: zoeyvid-bot
services:
  zoeyvid-bot:
    container_name: zoeyvid-bot
    restart: unless-stopped
    image: zoeyvid/zoeyvid-bot:latest # or ghcr.io/zoeyvid/zoeyvid-bot:latest
    pull_policy: always
    network_mode: bridge
#    ports:
#      - "127.0.0.1:2020:2020"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - "/opt/zoeyvid-bot.json:/app/config.json:ro"
    environment:
      TZ: Europe/Berlin
